.TH "src/graphics/graphics.ixx" 3 "Paladin3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphics/graphics.ixx
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgraphics\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgraphics::vk_createInstance\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Paladin3D from the source code\&.
