.TH "graphics" 3 "Paladin3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgraphics::vk_createInstance\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "auto \fBappName\fP = 'Paladin3D'"
.br
.ti -1c
.RI "auto \fBengineName\fP = 'Paladin3D'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void graphics::vk_createInstance ()\fR [export]\fP"

.SH "Variable Documentation"
.PP 
.SS "auto graphics::appName = 'Paladin3D'"

.SS "auto graphics::engineName = 'Paladin3D'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Paladin3D from the source code\&.
