.TH "src/graphics/instance.cpp" 3 "Paladin3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphics/instance.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <vulkan/vulkan\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgraphics\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgraphics::vk_createInstance\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "auto \fBgraphics::appName\fP = 'Paladin3D'"
.br
.ti -1c
.RI "auto \fBgraphics::engineName\fP = 'Paladin3D'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Paladin3D from the source code\&.
